### PR TITLE
document category options

### PR DESCRIPTION
**Pull request by aciccarello**
Adds descriptions of the new `@category` decorator and options.

Related to TypeStrong/typedoc#566 TypeStrong/typedoc#938

### CODE REVIEW

**Comment by aciccarello** [comment]
@jonchardy Could you review this for accuracy?

**Comment by jonchardy** [comment]
Yep, looks good. Thanks!

**Comment by aciccarello** [comment]
Great! I'll leave this open until I put together a release

**Comment by aciccarello** [comment]
Reminder for myself: Need to update the `--help` output when the release is pushed.

**Pull request merged**
